apiVersion: v1
kind: Service
metadata:
  name: testapp-svc-1
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: testapp-svc-1
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testapp-svc-1
  name: testapp-svc-1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: testapp-svc-1
  template:
    metadata:
      labels:
        app: testapp-svc-1
    spec:
      containers:
      - image: ratnadeepb/testapp:base
        name: testapp-svc-1
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 1
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      - image: ratnadeepb/micoproxy:latest
        name: micoproxy
        ports:
        - containerPort: 62081
        - containerPort: 62082
        securityContext:
          allowPrivilegeEscalation: y
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: y
          runAsUser: 2102
      initContainers:
      - command:
        - /usr/local/micoinit
        image: ratnadeepb/micoinit:latest
        name: mico-init1
        securityContext:
          privileged: y
      - args:
        - -t
        - nat
        - -L
        command:
        - iptables
        image: ratnadeepb/micoinit:latest
        name: mico-init2
        securityContext:
          allowPrivilegeEscalation: y
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          privileged: y
